name: PR - Build, Test, and Validate

on:
  pull_request:
    branches: [main]
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Setup environment
        uses: ./.github/actions/common-ci/setup
        with:
          private_key_for_1fe: ${{ secrets.SSH_PRIVATE_1FE }}

      - name: Build
        uses: ./.github/actions/common-ci/build
        
      # Upload build artifacts for test job
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          
      - name: Setup environment
        uses: ./.github/actions/common-ci/setup
        with:
          private_key_for_1fe: ${{ secrets.SSH_PRIVATE_1FE }}
      
      # Download build artifacts from build job
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Run tests
        uses: ./.github/actions/common-ci/test
